/*
CREATE TABLE PERSON(ID NUMBER(19), FIRSTNAME VARCHAR(50), LASTNAME VARCHAR2(50));
ALTER TABLE PERSON ADD CONSTRAINT PERSON_PK PRIMARY KEY(ID);
CREATE SEQUENCE PERSON_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

INSERT INTO PERSON(ID, FIRSTNAME, LASTNAME) VALUES(1000, 'ELIAS', 'LEVIS');
INSERT INTO PERSON(ID, FIRSTNAME, LASTNAME) VALUES(1001, 'FRODO', 'BUGGINS');

CREATE TABLE FAVORITE(ID NUMBER(19) NOT NULL, USERID VARCHAR2(64) NOT NULL, PROFILE VARCHAR2(50) NOT NULL, DESCR VARCHAR2(100) NOT NULL, OBJECTDATA CLOB NOT NULL);
ALTER TABLE FAVORITE ADD CONSTRAINT FAVORITE_PK PRIMARY KEY(ID);

CREATE SEQUENCE FAVORITE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
*/
insert into person(id, firstname, lastname) values(1000, 'ELIAS', 'LEVIS');
insert into person(id, firstname, lastname) values(1001, 'FRODO', 'BUGGINS');
